### ISSUE TITLE
打开时，提示“系统热键注册失败”

### ISSUE THREAD

**Issue by foxleeda** [LengSC/BossKey#1]
请问该如何解决？
已经使用管理员运行，依然会报错。
![Snipaste_2023-06-02_13-37-16](https://github.com/LengSC/BossKey/assets/60538873/7e93d21e-af12-47bf-8dff-28b98c9775e1)

**Comment by LengSC** [comment]
请问你是否同时打开了QQ？

**Comment by foxleeda** [comment]
是的，关闭qq后可以用了，谢谢

**Comment by LengSC** [comment]
好的！
出现错误的原因是：
本软件的快捷键之一为“Ctrl+Alt+S”，与QQ自带的截图快捷键发生冲突。
如果您想要在使用QQ的同时使用本软件，可以尝试在QQ的设置中关闭自带的截图。
